networks:
  default:
    name: clickhouse-local

services:
  clickhouse:
    container_name: clickhouse-local
    image: clickhouse/clickhouse-server:24.9.1
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: root
      CLICKHOUSE_PASSWORD: root
      CLICKHOUSE_DB: public
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native interface
    # Set limits on the number of open file descriptors clickhouse can have
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_local_data:/var/lib/clickhouse
      - clickhouse_local_logs:/var/log/clickhouse-server
    restart: unless-stopped

volumes:
  clickhouse_local_data:
  clickhouse_local_logs:
