networks:
  default:
    name: mysql-local

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: public
    ports:
      - "3306:3306"
    volumes:
      - mysql_local_data:/var/lib/mysql
    restart: unless-stopped


volumes:
  mysql_local_data:
