#!/usr/bin/env zsh

# Compare two JSON files semantically, with invariance to ordering and formatting
function jsondiff() {
  if [ $# -ne 2 ]; then
    echo "Usage: $0 <file1.json> <file2.json>"
    exit 1
  fi

  diff --color <(jq --sort-keys . "$1") <(jq --sort-keys . "$2")
}

jsondiff "$@"
