#!/usr/bin/env zsh
source ~/.zshrc

# Default to interactive mode
AUTO_APPROVE=false

if [[ "$1" == "-y" ]]; then
  AUTO_APPROVE=true
  echo "Running in non-interactive mode. All updates will be applied automatically."
fi

# Prompt user for confirmation
confirm() {
  local prompt="$1"
  local check_command="$2"
  local action="$3"

  if $AUTO_APPROVE; then
    eval "$action"
    return
  fi

  if [[ -n "$check_command" ]]; then
    echo "Checking for updates..."
    eval "$check_command"
  fi

  echo -n "\e[33m$prompt\e[0m [Y/n]: "
  read -r response

  if [[ "$response" =~ ^[Nn]$ ]]; then
    echo "Skipping this step..."
  else
    eval "$action"
  fi
}

echo "\e[3;94m=== Oh-My-Zsh ===\e[0m"
omz update

echo "\e[3;94m=== Homebrew ===\e[0m"
brew update
echo "Fetching outdated brew packages..."
brew upgrade --greedy --dry-run
confirm "Update Homebrew formulae?" \
  "" \
  "{ echo 'Updating brew formulae...';  brew upgrade; }"
confirm "Update Homebrew casks?" \
  "" \
  "{ echo 'Updating brew casks...'; brew upgrade --greedy --no-quarantine; }"
echo "Running cleanup..."
brew autoremove
brew cleanup

echo "\e[3;94m=== Rust and Cargo binaries ===\e[0m"
confirm "Update Rust and global Rust binaries?" \
"{ echo 'Rust version:'; rustup check; echo 'Cargo package versions:'; cargo install-update --list; }" \
"{ echo 'Updating global rust binaries...'; rustup update stable; cargo install-update --all; }"

echo "\e[3;94m=== Go binaries ===\e[0m"
confirm "Update global Go binaries?" \
"go-global-update --dry-run" \
"{ echo 'Updating global go binaries...'; go-global-update; }"

# uv tools update
echo "\e[3;94m=== uv tools ===\e[0m"
confirm "Update uv tools?" \
"" \
"{ uv tool upgrade --all }"

echo "\e[32mSystem update complete!\e[0m"
