#!/usr/bin/env zsh

# Process a file with `printf '%b'` and replace escaped quotes
# TODO: If no argument is provided, attempt to read and write from clipboard
function unescape() {
  if [ $# -ne 1 ]; then
    echo "Usage: $0 <file_path>"
    exit 1
  fi

  file_path="$1"
  if [ ! -f "$file_path" ]; then
      echo "Error: File '$file_path' does not exist"
      exit 1
  fi

  temp_file="${file_path}.tmp"
  printf '%b' "$(cat "$file_path")" > "$temp_file"
  sed 's/\\"/"/g' "$temp_file" > "$file_path"
  rm "$temp_file"
}

unescape "$@"
