#!/usr/bin/env zsh

# Converts a video(.mp4) to GIF format
function vidtogif() {
  if [ $# -ne 2 ]; then
    echo "Usage: $0 <input-file> <output-file>
    where input file is of type: .mp4, .webm, ...
    and output file is .gif"
    return
  fi
  gifski -r 10 "$1" -o "$2"
}

vidtogif "$@"
